# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY ./server ./server
COPY ./capa_intermedia ./capa_intermedia
RUN npx -y esbuild capa_intermedia/index.ts --bundle --platform=node --format=esm --target=node20 --packages=external --outfile=dist/capa_intermedia/index.js

# Stage 2: Producción
FROM node:20-alpine AS runner
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
RUN mkdir -p ./server
COPY --from=builder /app/dist/capa_intermedia/index.js ./capa_intermedia/index.js

EXPOSE 4001
CMD ["node", "capa_intermedia/index.js"]
